name: build and push
on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      use-cache:
        description: "Use cache for building the Docker image"
        required: false
        default: "true"
        type: string
    secrets:
      IS_DOCKER_HUB_USERNAME:
        required: true
      IS_DOCKER_HUB_PASSWORD:
        required: true
      build_args:
        required: false
    outputs:
      digest:
        description: "The digest of the docker image."
        value: ${{ jobs.build-and-push.outputs.digest }}

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-20.04
    outputs:
      digest: ${{ steps.docker_build.outputs.digest }}
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.IS_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.IS_DOCKER_HUB_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ inputs.tags }}
          cache-from: ${{ inputs.use-cache == 'true' && 'type=registry,ref=expedient/cache' || '' }}
          cache-to: ${{ inputs.use-cache == 'true' && 'type=registry,ref=expedient/cache' || '' }}
          build-args: ${{ secrets.build_args }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
