name: golangci-lint
on:
  workflow_call:
    inputs:
      GO_VERSION:
        default: '1.22'
        type: string
    secrets:
      IS_GITHUB_USERNAME:
        required: true
      IS_GITHUB_TOKEN:
        required: true
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/expedient"
    steps:
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.IS_GITHUB_TOKEN }}
          USERNAME: ${{ secrets.IS_GITHUB_USERNAME }}
        run: |
          git config --global url."https://${USERNAME}:${TOKEN}@github.com".insteadOf "https://github.com" && \
          export GOPRIVATE="github.com/expedient"
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.GO_VERSION }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.57.2
