name: golangci-lint
on:
  workflow_call:
    inputs:
      GO_VERSION:
        default: 1.17
        type: string
    secrets:
      IS_GITHUB_USERNAME:
        required: true
      IS_GITHUB_TOKEN:
        required: true
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.GO_VERSION }}
      - uses: actions/checkout@v3
      - run: |
          RUN echo "machine github.com" > /root/.netrc
          RUN echo "login ${{ secrets.IS_GITHUB_USERNAME }}" >> /root/.netrc
          RUN echo "password ${{ secrets.IS_GITHUB_TOKEN }}" >> /root/.netrc
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
