name: Kustomize Deploy Commit
on:
  workflow_call:
    inputs:
      KUBERNETES_REPO:
        description: 'The GitHub repository to deploy to'
        required: true
        type: string
      KUBERNETES_REPO_REF:
        description: 'The GitHub repository reference to deploy to'
        required: false
        type: string
        default: 'master'
      GITHUB_EMAIL:
        required: true
        type: string
      APPLICATION:
        required: true
        type: string
      KUSTOMIZE_PATH:
        required: false
        type: string
        default: kustomize/overlays/instances
      CLUSTERS:
        description: 'The list of cluster instances to deploy to'
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      IMAGE_DIGEST:
        required: true
        type: string
    secrets:
      IS_CICD_GITHUB_ACTION_TOKEN:
        required: true

jobs:
  kustomize-deploy-commit:
    runs-on: ubuntu-20.04
    name: kustomize-deploy-commit
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.KUBERNETES_REPO }}
          fetch-depth: 0
          ref: '${{ inputs.KUBERNETES_REPO_REF }}'
          token: ${{ secrets.IS_CICD_GITHUB_ACTION_TOKEN }}

      - name: Update kubernetes resources
        uses: stefanprodan/kube-tools@v1

      - name: Setup git
        run: |
          git config --global user.name "github-action-bot"
          git config --global user.email "${{ inputs.GITHUB_EMAIL }}"

      - name: Update image digest for each cluster
        run: |
          clusters="${{ inputs.CLUSTERS }}"
          a=($(echo "$clusters" | tr ',' '\n'))
          for i in "${a[@]}"
          do
            echo "Updating image digest for $i"
            (set -eux; cd applications/${{ inputs.APPLICATION }}/${{ inputs.KUSTOMIZE_PATH }}/$i && kustomize edit set image ${{ inputs.APPLICATION }}@${{ inputs.IMAGE_DIGEST }})
            if [ $? -ne 0 ]; then
            echo "Instance $i not found"
            exit 1
            fi
          done

      - name: Update the deployed app version
        if: ${{ github.event.inputs.version != '' }}
        uses: mikefarah/yq@v4.18.1
        with:
          cmd: yq -i '.spec.template.spec.containers[1].env[0].value = "${{ github.event.inputs.version }}"' applications/${{ inputs.APPLICATION }}/kustomize/overlays/environments/${{ inputs.ENVIRONMENT }}/deployment.yaml

      - name: Git commit the updated image tag
        # Only commits if there are changes.
        run: |
          git add .
          git update-index --refresh
          git diff-index --quiet HEAD || git commit -m "Set ${{ inputs.APPLICATION }} ${{ inputs.ENVIRONMENT }} image digest to ${{ inputs.IMAGE_DIGEST }}"

      - name: Git push changes
        run: |
          git status
          git push
